# Scratch Pad

## Install Packages

In [45]:
import pandas as pd
import os

## Import Data

In [54]:
# Using relative path - go up one level from notebooks folder
data_path = '../data/final_collision_data.csv'

# Verify the path (optional - you can remove this later)
print(f"Loading data from: {os.path.abspath(data_path)}")

# read the data
collision_data_merged = pd.read_csv(data_path)
collision_data_merged.head()

Loading data from: /Users/ko/Documents/Projects/NYCOpenData/Collision Data/data/final_collision_data.csv

/var/folders/zd/7hy4ychs2_sfhq3qhwhl6qf80000gn/T/ipykernel_55324/3391228848.py:8: DtypeWarning: Columns (3,20,23,24,26,28,29,30,32,33,34,35,36,37,39,43,47,48,49,50,51,52,53,54,55,56,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  collision_data_merged = pd.read_csv(data_path)

,crash_date,crash_time,borough,zip_code,latitude,longitude,on_street_name,off_street_name,cross_street_name,number_of_persons_injured,...,position_in_vehicle,safety_equipment,ped_location,ped_action,complaint,ped_role,person_contributing_factor_1,person_contributing_factor_2,person_sex,merge_key_person
0,2017-08-16,10:00,NaN,NaN,40.798256,-73.92402,TRIBOROUGH BRIDGE,NaN,NaN,0.0,...,Driver,Lap Belt & Harness,NaN,NaN,Does Not Apply,Driver,NaN,NaN,M,3732163_17620853
1,2017-08-16,10:00,NaN,NaN,40.798256,-73.92402,TRIBOROUGH BRIDGE,NaN,NaN,0.0,...,Driver,Lap Belt & Harness,NaN,NaN,Does Not Apply,Driver,NaN,NaN,M,3732163_17620854
2,2017-08-16,10:00,NaN,NaN,40.798256,-73.92402,TRIBOROUGH BRIDGE,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,Registrant,NaN,NaN,U,3732163_17620854
3,2017-08-16,10:00,NaN,NaN,40.798256,-73.92402,TRIBOROUGH BRIDGE,NaN,NaN,0.0,...,Driver,Lap Belt & Harness,NaN,NaN,Does Not Apply,Driver,NaN,NaN,F,3732163_17620855
4,2017-07-29,21:50,BROOKLYN,11206.0,40.707333,-73.94321,GRAHAM AVENUE,MONTROSE AVENUE,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
collision_data_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2198431 entries, 0 to 2198430
Data columns (total 60 columns):
 #   Column                         Dtype
---  ------                         -----
 0   crash_date                     object
 1   crash_time                     object
 2   borough                        object
 3   zip_code                       object
 4   latitude                       float64
 5   longitude                      float64
 6   on_street_name                 object
 7   off_street_name                object
 8   cross_street_name              object
 9   number_of_persons_injured      float64
 10  number_of_persons_killed       float64
 11  number_of_pedestrians_injured  int64
 12  number_of_pedestrians_killed   int64
 13  number_of_cyclist_injured      int64
 14  number_of_cyclist_killed       int64
 15  number_of_motorist_injured     int64
 16  number_of_motorist_killed      int64
 17  collision_id                   int64
 18  event_collision_factors        object
 19  unique_id                      float64
 20  vehicle_id                     object
 21  state_registration             object
 22  vehicle_type                   object
 23  vehicle_make                   object
 24  vehicle_model                  object
 25  vehicle_year                   float64
 26  travel_direction               object
 27  vehicle_occupants              float64
 28  driver_sex                     object
 29  driver_license_status          object
 30  driver_license_jurisdiction    object
 31  pre_crash                      object
 32  point_of_impact                object
 33  vehicle_damage                 object
 34  vehicle_damage_2               object
 35  vehicle_damage_3               object
 36  public_property_damage         object
 37  public_property_damage_type    object
 38  vehicle_contributing_factor_1  object
 39  vehicle_contributing_factor_2  object
 40  merge_key_vehicle              object
 41  unique_id_person               float64
 42  collision_id_person            float64
 43  person_id                      object
 44  person_type                    object
 45  vehicle_id_person              float64
 46  person_age                     float64
 47  ejection                       object
 48  emotional_status               object
 49  bodily_injury                  object
 50  position_in_vehicle            object
 51  safety_equipment               object
 52  ped_location                   object
 53  ped_action                     object
 54  complaint                      object
 55  ped_role                       object
 56  person_contributing_factor_1   object
 57  person_contributing_factor_2   object
 58  person_sex                     object
 59  merge_key_person               object
dtypes: float64(11), int64(7), object(42)
memory usage: 1006.4+ MB

## Single Collision Finder

In [ ]:
# Filter using collision ID
collision_data_preview = collision_data_merged[collision_data_merged['collision_id'] == 4030165]
collision_data_preview.to_csv('collision_data_preview.csv', index=False)